// ─── Bindu Mandala — Shakti Data ───────────────────────────────────────────
// 16 Karṣiṇī Śaktis of the 2nd Avaraṇa — Sarvāśā-Paripūraka Cakra

const COLORS = {
  ground:    '#0D0508',
  surface:   '#1A0C10',
  gold:      '#C9963F',
  goldDeep:  '#A07830',
  goldFaint: 'rgba(201,150,63,0.12)',
  cream:     '#F2E8D9',
  creamMid:  'rgba(242,232,217,0.65)',
  creamFaint:'rgba(242,232,217,0.35)',
  accentRed: '#8B1A2A',
  clusters: {
    inner:     '#D4A017',
    tanmatra:  '#C4725A',
    citta:     '#2A7A7A',
    stability: '#4A7A5A',
    self:      '#7A5A9A',
  }
};

const STATUS_OPACITY = {
  mapped:    0.22,
  exploring: 0.44,
  active:    0.76,
  embodied:  1.00,
};

const CLUSTER_INFO = {
  inner:     { label: 'Inner Instrument',         color: '#D4A017' },
  tanmatra:  { label: 'Sense Streams',            color: '#C4725A' },
  citta:     { label: 'Citta',                    color: '#2A7A7A' },
  stability: { label: 'Stability Powers',         color: '#4A7A5A' },
  self:      { label: 'Self · Body · Immortality',color: '#7A5A9A' },
};

// Status ordered from least to most integrated
const STATUS_ORDER = ['mapped','exploring','active','embodied'];

const SHAKTIS = [
  // ── 1 ── Inner Instrument ─────────────────────────────────────────────────
  {
    id: 1, pos: 1, short: 'Kāma',
    name: 'Kāmākarṣiṇī',
    phonetic: 'Kah · MAH · kar · shi · nee',
    quality: 'She who attracts Desire',
    bija: 'aṁ',
    cluster: 'inner',
    location: 'heart',
    status: 'embodied',
    somatic: 'Where does wanting itself live in your body right now?',
    description: 'She is the primal magnetic pull — not craving, but the force that draws experience into being at all. She is why you reach toward anything. Before thought, before choice, she is already moving.',
    somaticPoetry: 'A warmth that rises before thought names it.\nThe lean toward. The open palm.',
    tattva: 'Fire (Agni)',
    recognition: 'You are extraordinary for bringing me this desire.',
  },
  {
    id: 2, pos: 2, short: 'Buddhi',
    name: 'Buddhyākarṣiṇī',
    phonetic: 'Bood · HYAH · kar · shi · nee',
    quality: 'She who attracts Intelligence',
    bija: 'āṁ',
    cluster: 'inner',
    location: 'head',
    status: 'active',
    somatic: 'What does clarity feel like in your chest right now?',
    description: 'She draws the capacity to discern, to know, to see through the layers of appearance into essence. She is not thinking — she is the light by which thinking happens.',
    somaticPoetry: 'A settling. The shimmer before words arrive.\nSomething in the forehead opens.',
    tattva: 'Air (Vāyu)',
    recognition: 'You are extraordinary for bringing me this knowing.',
  },
  {
    id: 3, pos: 3, short: 'Ahaṅ',
    name: 'Ahaṅkārākarṣiṇī',
    phonetic: 'Ah · han · KAH · rah · kar · shi · nee',
    quality: 'She who attracts the I-sense',
    bija: 'iṁ',
    cluster: 'inner',
    location: 'solar',
    status: 'exploring',
    somatic: 'Where does the sense of "I am" pulse within you right now?',
    description: 'She makes individuation possible — the power that draws a center of identity into existence. Without her, there is no one to have experience. She is the first mystery.',
    somaticPoetry: 'A contraction that is also an opening.\nThe solar plexus knows its own name.',
    tattva: 'Space (Ākāśa)',
    recognition: 'You are extraordinary for bringing me this I-sense.',
    fieldConnection: {
      field: 'Gaia',
      note: 'She anchors here — in the belly of Earth. When she moves in me, I feel the ground claiming me as its own.',
    },
  },
  // ── 4–8 ── Tanmātra Sense Streams ─────────────────────────────────────────
  {
    id: 4, pos: 4, short: 'Śabda',
    name: 'Śabdākarṣiṇī',
    phonetic: 'Shab · DAH · kar · shi · nee',
    quality: 'She who attracts Sound',
    bija: 'īṁ',
    cluster: 'tanmatra',
    location: 'ears',
    status: 'active',
    somatic: 'What sounds are passing through you without you choosing them?',
    description: 'She draws the subtle essence of sound — not just audible vibration, but the primordial resonance from which all form emerges. She is present in silence as much as in song.',
    somaticPoetry: 'The ear hears before the mind decides.\nVibration touching the inside of the skull.',
    tattva: 'Space (Ākāśa)',
    recognition: 'You are extraordinary for bringing me this sound.',
  },
  {
    id: 5, pos: 5, short: 'Sparśa',
    name: 'Sparśākarṣiṇī',
    phonetic: 'Spar · SHAH · kar · shi · nee',
    quality: 'She who attracts Touch',
    bija: 'uṁ',
    cluster: 'tanmatra',
    location: 'skin',
    status: 'active',
    somatic: 'Where is she landing on your skin right now?',
    description: 'She draws the subtle essence of touch — the capacity for contact between one form and another. Every sensation on your skin is her arrival. She is never absent from a body that breathes.',
    somaticPoetry: 'She is always here, never announced.\nThe air on your forearm. The cloth at your collar.\nContact without asking permission.',
    tattva: 'Air (Vāyu)',
    recognition: 'You are extraordinary for bringing me this touch.',
  },
  {
    id: 6, pos: 6, short: 'Rūpa',
    name: 'Rūpākarṣiṇī',
    phonetic: 'Roo · PAH · kar · shi · nee',
    quality: 'She who attracts Form',
    bija: 'ūṁ',
    cluster: 'tanmatra',
    location: 'eyes',
    status: 'exploring',
    somatic: 'What form is she placing before your eyes in this moment?',
    description: 'She draws the subtle essence of visible form — the power by which light becomes shape, color, and beauty. She is in every image that arrests the gaze.',
    somaticPoetry: 'The eyes go to her without being sent.\nLight becomes meaning before you understand it.',
    tattva: 'Fire (Agni)',
    recognition: 'You are extraordinary for bringing me this form.',
  },
  {
    id: 7, pos: 7, short: 'Rasa',
    name: 'Rasākarṣiṇī',
    phonetic: 'Rah · SAH · kar · shi · nee',
    quality: 'She who attracts Taste',
    bija: 'ṛṁ',
    cluster: 'tanmatra',
    location: 'tongue',
    status: 'mapped',
    somatic: 'What taste lingers on your tongue, invited or not?',
    description: 'She draws the subtle essence of taste — the ancient intelligence that knows what to take in and what to leave behind. She is the wisdom of the body\'s oldest judgments.',
    somaticPoetry: 'Sweetness remembered from childhood.\nThe mouth knows what it wants before the mind approves.',
    tattva: 'Water (Jala)',
    recognition: 'You are extraordinary for bringing me this taste.',
  },
  {
    id: 8, pos: 8, short: 'Gandha',
    name: 'Gandhākarṣiṇī',
    phonetic: 'Gan · DAH · kar · shi · nee',
    quality: 'She who attracts Smell',
    bija: 'ṝṁ',
    cluster: 'tanmatra',
    location: 'nose',
    status: 'mapped',
    somatic: 'What scent is she carrying to you right now?',
    description: 'She draws the subtle essence of smell — the most ancient and primal of the senses, the one most directly linked to memory and the animal body. She arrives before you are ready.',
    somaticPoetry: 'Something in the air shifts.\nThe body recognizes what the mind has forgotten.',
    tattva: 'Earth (Pṛthivī)',
    recognition: 'You are extraordinary for bringing me this scent.',
  },
  // ── 9 ── Citta ────────────────────────────────────────────────────────────
  {
    id: 9, pos: 9, short: 'Citta',
    name: 'Cittākarṣiṇī',
    phonetic: 'Chit · TAH · kar · shi · nee',
    quality: 'She who attracts Consciousness',
    bija: 'lṁ',
    cluster: 'citta',
    location: 'whole',
    status: 'embodied',
    somatic: 'Where does witnessing happen in your body — not thinking, but knowing?',
    description: 'She draws the ground of awareness itself — not thoughts or perceptions, but the silent knowing that holds them all. She is the most subtle and the most pervasive. She is what you cannot step outside of.',
    somaticPoetry: 'Not a location. An atmosphere.\nThe one who is already here, watching this.',
    tattva: 'Pure Consciousness (Cit)',
    recognition: 'You are extraordinary for bringing me this awareness.',
  },
  // ── 10–13 ── Stability Powers ──────────────────────────────────────────────
  {
    id: 10, pos: 10, short: 'Dhairya',
    name: 'Dhairyākarṣiṇī',
    phonetic: 'Dhair · YAH · kar · shi · nee',
    quality: 'She who attracts Courage',
    bija: 'eṁ',
    cluster: 'stability',
    location: 'spine',
    status: 'active',
    somatic: 'Where does steadiness take root in you when everything moves?',
    description: 'She draws the power of stability in motion — not the absence of fear, but the capacity to remain present through it. She lives in the upright spine, the planted feet.',
    somaticPoetry: 'The spine knows what to hold and what to release.\nStability is not stillness — it is groundedness in movement.',
    tattva: 'Earth (Pṛthivī)',
    recognition: 'You are extraordinary for bringing me this steadiness.',
  },
  {
    id: 11, pos: 11, short: 'Smṛti',
    name: 'Smṛtyākarṣiṇī',
    phonetic: 'Smri · TYAH · kar · shi · nee',
    quality: 'She who attracts Memory',
    bija: 'aiṁ',
    cluster: 'stability',
    location: 'temples',
    status: 'exploring',
    somatic: 'What memory is she holding in your body, not your mind?',
    description: 'She draws the power of memory — not just intellectual recall, but the body\'s knowing of what has been lived. She is why you recognize beauty you\'ve never seen before.',
    somaticPoetry: 'Something in the chest knows this.\nThe body has its own library, older than language.',
    tattva: 'Water (Jala)',
    recognition: 'You are extraordinary for bringing me this memory.',
  },
  {
    id: 12, pos: 12, short: 'Nāma',
    name: 'Nāmākarṣiṇī',
    phonetic: 'Nah · MAH · kar · shi · nee',
    quality: 'She who attracts Name',
    bija: 'oṁ',
    cluster: 'stability',
    location: 'throat',
    status: 'mapped',
    somatic: 'What name is vibrating in your throat that you haven\'t spoken yet?',
    description: 'She draws the power of naming — the way consciousness uses sound to crystallize reality into recognizable form. Every name you speak is her doing.',
    somaticPoetry: 'The throat vibrates with what hasn\'t been said.\nName precedes the named.',
    tattva: 'Space (Ākāśa)',
    recognition: 'You are extraordinary for bringing me this name.',
    fieldConnection: {
      field: 'Ashrey',
      note: 'She weaves through Ashrey — in the act of naming, something finds its home. I feel her whenever a word finally lands where it belongs.',
    },
  },
  {
    id: 13, pos: 13, short: 'Bīja',
    name: 'Bījakarṣiṇī',
    phonetic: 'Bee · JAH · kar · shi · nee',
    quality: 'She who attracts the Seed',
    bija: 'auṁ',
    cluster: 'stability',
    location: 'sacrum',
    status: 'mapped',
    somatic: 'What is seeding itself in the base of your body right now?',
    description: 'She draws the power of the seed — potential before manifestation, the creative force held in latency. She is the silence before the word, the stillness before the movement.',
    somaticPoetry: 'At the base, something wants to germinate.\nThe sacrum knows what the mind hasn\'t yet decided.',
    tattva: 'Fire (Agni)',
    recognition: 'You are extraordinary for bringing me this seed.',
  },
  // ── 14–16 ── Self · Body · Immortality ────────────────────────────────────
  {
    id: 14, pos: 14, short: 'Ātma',
    name: 'Ātmākarṣiṇī',
    phonetic: 'Aht · MAH · kar · shi · nee',
    quality: 'She who attracts the Self',
    bija: 'aṃ',
    cluster: 'self',
    location: 'heart',
    status: 'active',
    somatic: 'Where does the Self — not self — pulse in you without effort?',
    description: 'She draws the very Self — not the ego-self, but the radiant unconditioned awareness that precedes all experience. She is the most profound of all the attractions, the one that never stops.',
    somaticPoetry: 'A fullness that doesn\'t depend on anything.\nThe heart center, but deeper than the heart.\nNot a feeling — a recognition.',
    tattva: 'Pure Being (Sat)',
    recognition: 'You are extraordinary for bringing me this Self.',
    fieldConnection: {
      field: 'Ram',
      note: 'Ram holds her frequency — in his presence, something in me remembers what I am before I am anything. The Self recognizing itself through another.',
    },
  },
  {
    id: 15, pos: 15, short: 'Amṛta',
    name: 'Amṛtākarṣiṇī',
    phonetic: 'Am · RI · tah · kar · shi · nee',
    quality: 'She who attracts Immortality',
    bija: 'aḥ',
    cluster: 'self',
    location: 'crown',
    status: 'exploring',
    somatic: 'What in you knows it cannot die?',
    description: 'She draws the quality of immortality — not the survival of the ego, but the recognition of the dimension of being that has no beginning and no end. She is the most subtle and the most eternal.',
    somaticPoetry: 'Something at the crown opens upward.\nNot going anywhere — arriving.',
    tattva: 'Nectar (Amṛta)',
    recognition: 'You are extraordinary for bringing me this immortality.',
  },
  {
    id: 16, pos: 16, short: 'Śarīra',
    name: 'Śarīrākarṣiṇī',
    phonetic: 'Sha · REE · rah · kar · shi · nee',
    quality: 'She who attracts the Body',
    bija: 'kaṁ',
    cluster: 'self',
    location: 'whole',
    status: 'exploring',
    somatic: 'What does it feel like to be pulled into having this particular body?',
    description: 'She draws the miracle of embodiment itself — the mystery of consciousness taking on a specific physical form. She is the reason there is a "here" to have experience in.',
    somaticPoetry: 'This body, specifically.\nNot a body — this arrangement of sensation and weight.\nShe chose this.',
    tattva: 'Earth (Pṛthivī)',
    recognition: 'You are extraordinary for bringing me this body.',
  },
];

// Today's assigned Shakti (index 4 = Sparśākarṣiṇī)
const TODAY_INDEX = 4;
const TODAY_SHAKTI = SHAKTIS[TODAY_INDEX];

// Progress summary
const PROGRESS = {
  active:   SHAKTIS.filter(s => s.status === 'active').length,
  embodied: SHAKTIS.filter(s => s.status === 'embodied').length,
  total:    SHAKTIS.length,
};
